# https://developers.home-assistant.io/docs/dev_101_services
# https://www.home-assistant.io/docs/blueprint/selectors/
run:
  name: Run
  description: Run an Omni-Assist voice pipeline
  fields:
    stream_source:
      name: Stream URL
      description: Link to stream (any type, supported by FFmpeg)
      example: rtsp://rtsp:12345678@192.168.1.123:554/av_stream/ch0
      selector:
        text:

    camera_entity_id:
      name: Camera Entity
      description: Entity for STT source
      selector:
        entity:
          domain: camera
          supported_features:
            - camera.CameraEntityFeature.STREAM

    player_entity_id:
      name: Player Entity
      description: Entity for playing TTS
      selector:
        entity:
          domain: media_player
          supported_features:
            - media_player.MediaPlayerEntityFeature.PLAY_MEDIA

    stt_start_media:
      name: STT start media
      description: Link to the media for playing on STT start
      selector:
        text:

    stt_end_media:
      name: STT end media
      description: Link to the media for playing on STT end
      selector:
        text:

    stt_error_media:
      name: STT error media
      description: Link to the media for playing on STT error
      selector:
        text:

    cancellation_media:
      name: Cancellation media
      description: Link to the media for playing when cancellation phrase is detected
      selector:
        text:

    pipeline_id:
      name: Pipeline
      description: Settings > Voice Assistant
      selector:
        assist_pipeline:

    device_id:
      name: Device ID
      description: The specific Omni-Assist device to run this pipeline on
      example: "omni_assist_device_123"
      selector:
        device:
          integration: omni_assist

    text_input:
      name: Text Input
      description: Text to process (only used when start_stage is 'intent')
      example: "Turn on the kitchen lights"
      selector:
        text:

    start_stage:
      name: Start Stage
      description: The pipeline stage to start from (default follows device configuration)
      example: "intent"
      selector:
        select:
          options:
            - "wake_word"
            - "stt"
            - "intent"

    request_followup:
      name: Request Follow-up
      description: Automatically start a new pipeline at STT stage after TTS completes
      default: false
      selector:
        boolean:

    conversation_id:
      name: Conversation ID
      description: Specific conversation ID to continue (for advanced use)
      selector:
        text:

    assist:
      name: Assist
      description: Advanced parameters
      selector:
        object:

    stream:
      name: Stream
      description: Advanced parameters
      selector:
        object:
